### PR TITLE
Release/1.4.0

### PR DESCRIPTION
**Pull request by kjaym**
See #85

### CODE REVIEW

**Comment by maxhutch** [comment]
LGTM.  @sinistral do you still want to block on backend robustness?

**Comment by eantono** [comment]
@kjaym @maxhutch @sinistral bump

**Comment by sinistral** [comment]
Sorry, I've lost the context on this one.  What were the backend robustness issues, @maxhutch?  I recall blocking another PR on changes that I was concerned were not backwards compatible, but @mcgalcode addressed those.

**Comment by eantono** [comment]
I think it was blocking on rate limiting the predict requests.

**Comment by sparadiso** [comment]
@jsomara have we implemented rate limiting for the predict api? I think @sinistral is concerned about the fact this can be used to DOS our site w/o rate limiting (Erin rate limits in her scripts, currently).

**Comment by eantono** [comment]
@jsomara bump

**Comment by maxhutch** [comment]
@jsomara is this still blocked?

**Pull request merged**
