### PR TITLE
Bump limit from 50k to 200k

### PR DESCRIPTION
**Pull request by genfx999**
CT-604

### CODE REVIEW

**Comment by genfx999** [comment]
This does not change the limit on number of rows you can get at once from search.  This limit increase is meant to allow pagination across >50k datasets.  The pycc error check does something like query.from + query.size > MAX_QUERY_LIMIT.  So even asking for 1 record passed the 50k line would fail.

**Comment by genfx999** [comment]
Thats fair, lets see if we can get DE folks to test off this branch.

**Comment by matSciMalcolm** [comment]
Hi All,

I put together the following notebook for testing: https://drive.google.com/file/d/1Ol37XhyzU8oN5-7fGtOIgOffPr1Wyawd/view?usp=sharing

Running on 06/24/2019 I did not receive the pagination error when going above n=50000. However, when I inspected the results it looks like each block of `extracted` is identical. Perhaps I wrote the query wrong?

**Comment by matSciMalcolm** [comment]
I also tested today using the script I prepared for the JIRA card and I ran into the `500` once pagination exceeded 50k. That script uses `generate_simple_chemical_query` instead of a `PifSystemReturningQuery` although I believe they are one in the same.

**Comment by genfx999** [comment]
On the query, the from_index and size fields can be applied anywhere, but they only seemed to work when I put them on the PifSystemReturningQuery like:
query = PifSystemReturningQuery(
            from_index=n,
            size=10, # <- Change this to 10k
            query=DataQuery(
                dataset=DatasetQuery(
                    id=Filter(
                        equal=str(dataset_id))),
                system=PifSystemQuery(
                    chemical_formula=ChemicalFieldQuery(
                                extract_as='Chemical Formula'))))

**Comment by genfx999** [comment]
The error is coming from ES, not CSL directly:
Result window is too large, from + size must be less than or equal to: [50000] but was [50010]. See the scroll api for a more efficient way to request large data sets. This limit can be set by changing the [index.max_result_window] index level setting.",

The index.max_result_window is set by CSL when it creates the index.  It does appear we can change this on the fly without rebuilding, but I would like to test this on a low traffic instance to make sure there are no side-effects.

**Pull request closed without merging**
