### PR TITLE
Release 6.5.1

### PR DESCRIPTION
**Pull request by ventura-rivera**
This release includes a bugfix where imports were failing due to dependencies locations being represented with symbolic links (#318).

### CODE REVIEW

**Comment by ventura-rivera** [comment]
Not sure if I need to make a release branch to master to get those changes on pypi. Is this necessary?

**Comment by maxhutch** [comment]
It will be necessary for the release, but it shouldn't be necessary to test it.  Just point the requirements.txt file in e2e2 at the `develop` branch.  Then, after it is verified, we can cut a release.

**Comment by ventura-rivera** [comment]
@maxhutch, Terrance commented about doing that here:
https://github.com/CitrineInformatics/python-citrination-client/pull/318#issuecomment-662021360

Do you want us to do it again for the develop branch too?

**Comment by maxhutch** [comment]
> @maxhutch, Terrance commented about doing that here:
> [#318 (comment)](https://github.com/CitrineInformatics/python-citrination-client/pull/318#issuecomment-662021360)
> 
> Do you want us to do it again for the develop branch too?

No, I had missed that.  Works for me!

**Comment by ventura-rivera** [comment]
There is one test that this always seems to hang up on until eventually timing out. But it seems to happen randomly. @genfx999 are you familiar with this test?:

https://github.com/CitrineInformatics/python-citrination-client/blob/develop/citrination_client/data/tests/test_data_client.py#L133

**Comment by genfx999** [comment]
@ventura-rivera That travis build for pycc is pretty flaky.  Its green now.

**Comment by ventura-rivera** [comment]
Thanks!

**Pull request merged**
