### PR TITLE
Fix/create public dataset

### PR DESCRIPTION
**Pull request by sparadiso**

### CODE REVIEW

**Comment by sparadiso** [comment]
@jsomara this is me being the change I wish to see in the world.

The failing test is:

```
>       assert len(user_B.dataset_search(query).hits) == 1
E       assert 0 == 1
```

**Comment by jsomara** [comment]
@sparadiso  thanks - is this JIRA"d yet? if not ill do that now

**Comment by sparadiso** [comment]
@jsomara  https://citrine.atlassian.net/browse/CITR-1263

**Comment by mcgalcode** [comment]
closing because this too is wrapped up in the refactor PR

**Pull request closed without merging**
